"use client";

import { Button } from "@/app/lbcl/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/app/lbcl/components/ui/card";

const EXCEL_DATA = [
  {
    "id": 1,
    "type": "Meetings",
    "focusArea": "MR App rollout & discussion",
    "date": "01/11/25",
    "day": "Sat",
    "kraPlan": "MR app roll out & discussion",
    "morningMeeting": "NA",
    "timeFrom": "9.00am",
    "timeTo": "5.00pm",
    "market": "Colombo",
    "channel": "NA",
    "routeNo": "NA",
    "outletNo": "NA",
    "accompaniedBy": "Sales & Marketing",
    "nightOut": "Colombo",
    "noOfDays": 1,
    "plannedMileage": 55
  },
  {
    "id": 2,
    "type": "Meetings",
    "focusArea": "F26 insights & planning",
    "date": "02/11/25",
    "day": "Sun",
    "kraPlan": "Annual planning insights",
    "morningMeeting": "NA",
    "timeFrom": "9.00am",
    "timeTo": "5.00pm",
    "market": "Colombo",
    "channel": "NA",
    "routeNo": "NA",
    "outletNo": "NA",
    "accompaniedBy": "Sales & Marketing",
    "nightOut": "Colombo",
    "noOfDays": 1,
    "plannedMileage": 55
  },
  {
    "id": 3,
    "type": "Meetings",
    "focusArea": "Operation Meeting",
    "date": "03/11/25",
    "day": "Mon",
    "kraPlan": "Discussion of operational matters with Sales Leadership team",
    "morningMeeting": "NA",
    "timeFrom": "9.00am",
    "timeTo": "5.00pm",
    "market": "TBC",
    "channel": "NA",
    "routeNo": "NA",
    "outletNo": "NA",
    "accompaniedBy": "Sales Leadership Team",
    "nightOut": "Colombo",
    "noOfDays": 1,
    "plannedMileage": 30
  },
  {
    "id": 4,
    "type": "Meetings",
    "focusArea": "Pre DPM & Training",
    "date": "07/11/25",
    "day": "Fri",
    "kraPlan": "Bottom up discussion & insights for improvements",
    "morningMeeting": "NA",
    "timeFrom": "9.00am",
    "timeTo": "5.00pm",
    "market": "Colombo",
    "channel": "NA",
    "routeNo": "NA",
    "outletNo": "NA",
    "accompaniedBy": "Sales Leadership Team",
    "nightOut": "Colombo",
    "noOfDays": 1,
    "plannedMileage": 40
  },
  {
    "id": 5,
    "type": "Meetings",
    "focusArea": "SFA Market Visit - WINTT",
    "date": "09/11/25",
    "day": "Sun",
    "kraPlan": "SFA market visit",
    "morningMeeting": "NA",
    "timeFrom": "9.00am",
    "timeTo": "5.00pm",
    "market": "Colombo",
    "channel": "NA",
    "routeNo": "NA",
    "outletNo": "NA",
    "accompaniedBy": "Sales Leadership Team",
    "nightOut": "Colombo",
    "noOfDays": 1,
    "plannedMileage": 50
  },
  {
    "id": 6,
    "type": "Meetings",
    "focusArea": "SFA Market Visit - WINTT",
    "date": "10/11/25",
    "day": "Mon",
    "kraPlan": "SFA market visit",
    "morningMeeting": "NA",
    "timeFrom": "9.00am",
    "timeTo": "5.00pm",
    "market": "Colombo",
    "channel": "NA",
    "routeNo": "NA",
    "outletNo": "NA",
    "accompaniedBy": "Sales Leadership Team",
    "nightOut": "Colombo",
    "noOfDays": 1,
    "plannedMileage": 40
  },
  {
    "id": 7,
    "type": "Meetings",
    "focusArea": "S & M Meeting",
    "date": "11/11/25",
    "day": "Tue",
    "kraPlan": "Last month Brand & Channel plans & activity review NM",
    "morningMeeting": "NA",
    "timeFrom": "9.00am",
    "timeTo": "5.00pm",
    "market": "Colombo",
    "channel": "NA",
    "routeNo": "NA",
    "outletNo": "NA",
    "accompaniedBy": "Sales & Marketing",
    "nightOut": "Colombo",
    "noOfDays": 1,
    "plannedMileage": 55
  },
  {
    "id": 8,
    "type": "Meetings",
    "focusArea": "CPM 01",
    "date": "15/11/25",
    "day": "Sat",
    "kraPlan": "Activity evaluation by base TMs & NM plans Channel & Brands",
    "morningMeeting": "NA",
    "timeFrom": "9.00am",
    "timeTo": "5.00pm",
    "market": "HO",
    "channel": "NA",
    "routeNo": "NA",
    "outletNo": "NA",
    "accompaniedBy": "Sales & Marketing",
    "nightOut": "Colombo",
    "noOfDays": 1,
    "plannedMileage": 180
  },
  {
    "id": 9,
    "type": "Meetings",
    "focusArea": "CPM 02",
    "date": "16/11/25",
    "day": "Sun",
    "kraPlan": "Review next month plans",
    "morningMeeting": "NA",
    "timeFrom": "9.00am",
    "timeTo": "5.00pm",
    "market": "HO",
    "channel": "NA",
    "routeNo": "NA",
    "outletNo": "NA",
    "accompaniedBy": "Sales & Marketing",
    "nightOut": "Colombo",
    "noOfDays": 1,
    "plannedMileage": 85
  },
  {
    "id": 10,
    "type": "Meetings",
    "focusArea": "Southern Cluster Meeting",
    "date": "23/11/25",
    "day": "Sun",
    "kraPlan": "Next month activity evaluation execusion & discussion",
    "morningMeeting": "NA",
    "timeFrom": "9.00am",
    "timeTo": "5.00pm",
    "market": "HO",
    "channel": "NA",
    "routeNo": "NA",
    "outletNo": "NA",
    "accompaniedBy": "Southern Cluster",
    "nightOut": "Colombo",
    "noOfDays": 1,
    "plannedMileage": 180
  },
  {
    "id": 11,
    "type": "Meetings",
    "focusArea": "F26 1st Cut PPT",
    "date": "24/11/25",
    "day": "Mon",
    "kraPlan": "F26 annual plan presentation - 1st cut",
    "morningMeeting": "NA",
    "timeFrom": "9.00am",
    "timeTo": "5.00pm",
    "market": "HO",
    "channel": "NA",
    "routeNo": "NA",
    "outletNo": "NA",
    "accompaniedBy": "Southern Cluster",
    "nightOut": "Colombo",
    "noOfDays": 1,
    "plannedMileage": 180
  },
  {
    "id": 12,
    "type": "Meetings",
    "focusArea": "Premium Meeting",
    "date": "25/11/25",
    "day": "Tue",
    "kraPlan": "MOFT & Horeca Discussion",
    "morningMeeting": "NA",
    "timeFrom": "9.00am",
    "timeTo": "5.00pm",
    "market": "HO",
    "channel": "NA",
    "routeNo": "NA",
    "outletNo": "NA",
    "accompaniedBy": "Sales & Marketing",
    "nightOut": "Colombo",
    "noOfDays": 1,
    "plannedMileage": 85
  },
  {
    "id": 13,
    "type": "Meetings",
    "focusArea": "F26 Plan Session 01",
    "date": "28/11/25",
    "day": "Fri",
    "kraPlan": "Presenting F26 Plan",
    "morningMeeting": "NA",
    "timeFrom": "9.00am",
    "timeTo": "5.00pm",
    "market": "HO",
    "channel": "NA",
    "routeNo": "NA",
    "outletNo": "NA",
    "accompaniedBy": "Sales & Marketing",
    "nightOut": "Colombo",
    "noOfDays": 1,
    "plannedMileage": 85
  },
  {
    "id": 14,
    "type": "Meetings",
    "focusArea": "F26 Plan Session 02",
    "date": "29/11/25",
    "day": "Sat",
    "kraPlan": "Presenting F26 Plan",
    "morningMeeting": "NA",
    "timeFrom": "9.00am",
    "timeTo": "5.00pm",
    "market": "HO",
    "channel": "NA",
    "routeNo": "NA",
    "outletNo": "NA",
    "accompaniedBy": "Sales & Marketing",
    "nightOut": "Colombo",
    "noOfDays": 1,
    "plannedMileage": 85
  },
  {
    "id": 15,
    "type": "Coaching/ Core Services Excellence (Core service audit/ TM Assessment)",
    "focusArea": "Boralasgamuwa",
    "date": "04/11/25",
    "day": "Tue",
    "kraPlan": "DCSLB conditional selling & operational issues",
    "morningMeeting": "Yes",
    "timeFrom": "8.00am",
    "timeTo": "5.00pm",
    "market": "Boralasgamuwa",
    "channel": "All",
    "routeNo": "NA",
    "outletNo": "10",
    "accompaniedBy": "TM",
    "nightOut": "Kaduwela",
    "noOfDays": 1,
    "plannedMileage": 55
  },
  {
    "id": 16,
    "type": "Coaching/ Core Services Excellence (Core service audit/ TM Assessment)",
    "focusArea": "Beruwala",
    "date": "08/11/25",
    "day": "Sat",
    "kraPlan": "Core service excellence & operational issues",
    "morningMeeting": "Yes",
    "timeFrom": "8.00am",
    "timeTo": "5.00pm",
    "market": "Beruwala",
    "channel": "All",
    "routeNo": "NA",
    "outletNo": "10",
    "accompaniedBy": "TM",
    "nightOut": "Kaduwela",
    "noOfDays": 1,
    "plannedMileage": 130
  },
  {
    "id": 17,
    "type": "Coaching/ Core Services Excellence (Core service audit/ TM Assessment)",
    "focusArea": "Galle",
    "date": "21/11/25",
    "day": "Fri",
    "kraPlan": "Core service & DCSLB penetration issues",
    "morningMeeting": "Yes",
    "timeFrom": "8.00am",
    "timeTo": "5.00pm",
    "market": "Galle",
    "channel": "All",
    "routeNo": "NA",
    "outletNo": "10",
    "accompaniedBy": "TM",
    "nightOut": "Galle",
    "noOfDays": 1,
    "plannedMileage": 180
  },
  {
    "id": 18,
    "type": "Coaching/ Core Services Excellence (Core service audit/ TM Assessment)",
    "focusArea": "Tangalle",
    "date": "30/11/25",
    "day": "Sun",
    "kraPlan": "Core service excellence & DCSL approaches",
    "morningMeeting": "Yes",
    "timeFrom": "8.00am",
    "timeTo": "5.00pm",
    "market": "Tangalle",
    "channel": "All",
    "routeNo": "NA",
    "outletNo": "10",
    "accompaniedBy": "TM",
    "nightOut": "Tangalle",
    "noOfDays": 1,
    "plannedMileage": 270
  },
  {
    "id": 19,
    "type": "Coaching/ Core Services Excellence (Core service audit/ TM Assessment)",
    "focusArea": "Tangalle",
    "date": "31/11/25",
    "day": "Mon",
    "kraPlan": "Core service excellence & DCSL approaches",
    "morningMeeting": "Yes",
    "timeFrom": "8.00am",
    "timeTo": "5.00pm",
    "market": "Tangalle",
    "channel": "All",
    "routeNo": "NA",
    "outletNo": "10",
    "accompaniedBy": "TM",
    "nightOut": "Tangalle",
    "noOfDays": 1,
    "plannedMileage": 270
  },
  {
    "id": 20,
    "type": "Observations / Night Visits",
    "focusArea": "Boralasgamuwa",
    "date": "03/11/25",
    "day": "Mon",
    "kraPlan": "MOFT LI visibility execusion",
    "morningMeeting": "NA",
    "timeFrom": "6.00pm",
    "timeTo": "10.00pm",
    "market": "Boralasgamuwa",
    "channel": "NA",
    "routeNo": "NA",
    "outletNo": "NA",
    "accompaniedBy": "TM",
    "nightOut": "Boralasgamuwa",
    "noOfDays": 1,
    "plannedMileage": 35
  },
  {
    "id": 21,
    "type": "Observations / Night Visits",
    "focusArea": "Beruwala",
    "date": "08/11/25",
    "day": "Sat",
    "kraPlan": "MOFT execusion & consumer behaviour",
    "morningMeeting": "NA",
    "timeFrom": "6.00pm",
    "timeTo": "10.00pm",
    "market": "Beruwala",
    "channel": "NA",
    "routeNo": "NA",
    "outletNo": "NA",
    "accompaniedBy": "TM",
    "nightOut": "Beruwala",
    "noOfDays": 1,
    "plannedMileage": 15
  },
  {
    "id": 22,
    "type": "Observations / Night Visits",
    "focusArea": "Galle",
    "date": "21/11/25",
    "day": "Fri",
    "kraPlan": "Observe TONT footfalls & consumer behaviour",
    "morningMeeting": "NA",
    "timeFrom": "6.00pm",
    "timeTo": "10.00pm",
    "market": "Galle",
    "channel": "NA",
    "routeNo": "NA",
    "outletNo": "NA",
    "accompaniedBy": "TM",
    "nightOut": "Galle",
    "noOfDays": 1,
    "plannedMileage": 15
  },
  {
    "id": 23,
    "type": "Observations / Night Visits",
    "focusArea": "Tangalle",
    "date": "30/10/25",
    "day": "Thu",
    "kraPlan": "Observe regular channel offtake trends",
    "morningMeeting": "NA",
    "timeFrom": "6.00pm",
    "timeTo": "10.00pm",
    "market": "Tangalle",
    "channel": "NA",
    "routeNo": "NA",
    "outletNo": "NA",
    "accompaniedBy": "TM",
    "nightOut": "Tangalle",
    "noOfDays": 1,
    "plannedMileage": 25
  },
  {
    "id": 24,
    "type": "Sales Planning/ Admin",
    "focusArea": "Admin",
    "date": "14/11/25",
    "day": "Fri",
    "kraPlan": "Complete for admin works & prepare for OPS meeting",
    "morningMeeting": "Yes",
    "timeFrom": "8.00am",
    "timeTo": "5.00pm",
    "market": "Negombo",
    "channel": "NA",
    "routeNo": "NA",
    "outletNo": "NA",
    "accompaniedBy": "TM",
    "nightOut": "Admin",
    "noOfDays": 1,
    "plannedMileage": 60
  },
  {
    "id": 25,
    "type": "Sales Planning/ Admin",
    "focusArea": "Admin",
    "date": "22/11/25",
    "day": "Sat",
    "kraPlan": "Preparation for cluster meeting",
    "morningMeeting": "Yes",
    "timeFrom": "8.00am",
    "timeTo": "5.00pm",
    "market": "Galle",
    "channel": "NA",
    "routeNo": "NA",
    "outletNo": "NA",
    "accompaniedBy": "TM",
    "nightOut": "Admin",
    "noOfDays": 1,
    "plannedMileage": 50
  },
  {
    "id": 26,
    "type": "Leave",
    "focusArea": "Personal matter",
    "date": "18/11/25",
    "day": "Tue",
    "kraPlan": "Personal matter",
    "morningMeeting": "NA",
    "timeFrom": "9.00am",
    "timeTo": "5.00pm",
    "market": "Colombo",
    "channel": "NA",
    "routeNo": "NA",
    "outletNo": "NA",
    "accompaniedBy": "TM",
    "nightOut": "Personal matter",
    "noOfDays": 1,
    "plannedMileage": 0
  }
];

export function ImportExcelData() {
  const handleImport = () => {
    if (confirm(`This will import ${EXCEL_DATA.length} entries from the Excel file to localStorage. Any existing data will be replaced. Continue?`)) {
      localStorage.setItem('itinerary_entries', JSON.stringify(EXCEL_DATA));
      alert(`✅ Successfully imported ${EXCEL_DATA.length} entries to localStorage!`);
      window.location.reload();
    }
  };

  const handleClear = () => {
    if (confirm('This will clear all itinerary entries from localStorage. Continue?')) {
      localStorage.removeItem('itinerary_entries');
      alert('✅ All entries cleared from localStorage!');
      window.location.reload();
    }
  };

  return (
    <Card className="max-w-2xl mx-auto mt-8">
      <CardHeader>
        <CardTitle>Import Excel Data to localStorage</CardTitle>
      </CardHeader>
      <CardContent className="space-y-4">
        <p className="text-sm text-gray-600">
          Import {EXCEL_DATA.length} entries from <strong>FSM_Itinerary Template2.xlsx</strong> directly to localStorage.
        </p>
        <div className="flex gap-3">
          <Button onClick={handleImport} className="bg-[#A08B5C] hover:bg-[#8A7548]">
            Import Excel Data
          </Button>
          <Button onClick={handleClear} variant="outline" className="text-red-600 border-red-600 hover:bg-red-50">
            Clear All Data
          </Button>
        </div>
      </CardContent>
    </Card>
  );
}
