using System;
using System.Collections.Generic;
using System.Text;

namespace Winit.Shared.Models.Constants
{
    public class CacheConstants
    {
        public const string ALL_CUSTOMERS = "ALL_CUSTOMERS";
        public const string ALL_Products = "ALL_Products";
        public const string ALL_ProductsConfig = "ALL_ProductsConfig";
        public const string ALL_ProductUOM = "ALL_ProductUOM";
        public const string ALL_ProductType = "ALL_ProductType";
        public const string ALL_ProductDimension = "ALL_ProductDimension";
        public const string ALL_ProductAttributes = "ALL_ProductAttributes";
        public const string ALL_BankDetails = "ALL_BankDetails";
        public const string ALL_SettingsDetails = "ALL_SettingsDetails";
        public const string ALL_OrgDetails = "ALL_OrgDetails";
        public const string ALLStoreAttributes = "ALL_StoreAttributes";
        public const string ALL_Store = "ALL_Store";
        public const string ALL_StoreSelectionItems = "ALL_StoreSelectionItems";
        public const string ALL_StoreGroup = "ALL_StoreGroup";
        public const string ALL_STORECREDIT = "ALL_STORECREDIT";
        public const string ALL_StoreAdditionalInfo = "ALL_StoreAdditionalInfo";
        public const string ALL_StoreGroupType = "ALL_StoreGroupType";
        public const string ALL_StoreSpecialDay = "ALL_StoreSpecialDay";
        public const string ALL_StoreToGroupMapping = "ALL_StoreToGroupMapping";
        public const string ALL_Holiday = "ALL_Holiday";
        public const string All_HolidayListRole = "All_HolidayListRole";
        public const string All_JobPosition = "All_JobPosition";
		public const string ALL_EmpDetails = "ALL_EmpDetails";
        public const string ALL_EmpInfoDetails = "ALL_EmpInfoDetails";
        public const string ALL_LocationDetails = "ALL_LocationDetails";
        public const string ALL_LocationMappingDetails = "ALL_LocationMappingDetails";
        public const string ALL_LocationTypeDetails = "ALL_LocationTypeDetails";
        public const string ALL_VehicleDetails = "ALL_VehicleDetails";
        public const string ALL_Route = "ALL_Route";
        public const string ALL_RouteCustomer = "ALL_RouteCustomer";
        public const string ALL_SKUPriceList = "ALL_SKUPriceList";
        public const string ALL_RouteUser = "ALL_RouteUser";
        public const string ALL_SKUPrice = "ALL_SKUPrice";
        public const string ALL_SKU = "ALL_SKU";
        public const string ALL_SKUMASTER = "ALL_SKUMASTER";
        public const string ALL_SKUConfig = "ALL_SKUConfig";
        public const string ALL_SKUAttributes = "ALL_SKUAttributes";
        public const string ALL_SKUGroupType = "ALL_SKUGroupType";
        public const string ALL_SKUToGroupMapping = "ALL_SKUToGroupMapping";
        public const string ALL_SKUClass = "ALL_SKUClass";
        public const string ALL_SKUClassGroup = "ALL_SKUClassGroup";
        public const string ALL_SKUClassGroupItems = "ALL_SKUClassGroupItems";
        public const string ALL_ContactDetails = "ALL_ContactDetails";
        public const string ALL_AddressDetails = "ALL_AddressDetails";
        public const string ALL_StoreDocumentDetails = "ALL_StoreDocumentDetails";
        public const string ALL_FileSysDetails = "ALL_FileSysDetails";
        public const string ALL_FileSysTemplateDetails = "ALL_FileSysTemplateDetails";
        public const string ALL_StoreWeekOff = "ALL_StoreWeekOff";
        public const string ALL_AWAYPERIOD = "ALL_AWAYPERIOD";
        public const string ALL_StoreCredit = "ALL_StoreCredit";
        public const string ALL_StoreAttributes = "ALL_StoreAttributes";
        public const string ALL_OrgCurrencyDetails = "ALL_OrgCurrencyDetails";
        public const string ALL_StoreDocument = "ALL_StoreDocument";
        public const string ALL_Setting = "ALL_Setting";
        public const string ALL_HolidayListDetails = "ALL_HolidayListDetails";
        public const string ALL_AwayPeriodDetails = "ALL_AwayPeriodDetails";
        public const string ALL_HolidayDetails = "ALL_HolidayDetails";
        public const string ALL_JobPositionDetails = "ALL_JobPositionDetails";
        public const string ALL_HolidayListRoleDetails = "ALL_HolidayListRoleDetails";
        public const string ALL_Product = "ALL_Product";
        public const string ALL_ReturnOrderDetails = "ALL_ReturnOrderDetails";
        public const string ALL_ReturnOrderLineDetails = "ALL_ReturnOrderLineDetails";
        public const string ALL_ReturnOrderTaxDetails = "ALL_ReturnOrderTaxDetails";
        public const string ELASTIC_STORE = "storerecord";
        public const string EmpDropDown = "EmpDropDown";
        public const string PromotionData = "Promotion_Data";
        public const string Location = "Location";
        public const string SKUMaster = "SKUMaster";
        public const string FilterSKUName = "Filter_SKU_Name_";
        public const string FilterSKUOrgUID = "Filter_SKU_OrgUID_";
        public const string SKUConfig = "SKUConfig";
        public const string SKUUOM = "SKUUOM";
        public const string SKUAttributes = "SKUAttributes";
        public const string TaxSKUMap = "TAXSKUMAP";
        public const string SKU = "SKU";
        public const string Org = "ORG";
        public const string Store = "STORE";
        public const string FilterStoreName = "Filter_Store_Name_";
        public const string FilterStoreType = "Filter_Store_Type_";
        public const string StoreAdditionalInfo = "STOREADDITIONALINFO";
        public const string StoreCredit = "STORECREDIT";
        public const string StoreAttributes = "STOREATTRIBUTES";
        public const string Addressses = "ADDRESSES";
        public const string Contacts= "CONTACTS";
        public const string StoreMaster = "STOREMASTER";
        public const string SKUAttributeLevelType = "SKUAttributeLevelType";
        public const string SKUAttributeLevel = "SKUAttributeLevel";
        public const string OrgCurrency = "ORGCURRENCY";
        public const string Setting = "SETTING_";
        public const string DefaultCreditType = "DefaultCreditType";
        public const string StoreLinkedItemUIDMapping = "Store_LinkedItemUID_Mapping";

    }
}
